### ISSUE TITLE
Use old oauth2client library

### ISSUE THREAD

**Issue by josele86** [googleads/googleads-python-lib#110]
This library use an old oauth2client library.
If I updated oauth2client library launchs and error because googleads library used SignedJwtAssertionCredentials that is droped.
This is a problem because an application uses google-api-python-client for connect to DCM or Google Analytics, like my case, in the last versions this not works because google-api-python-client uses last oauth2client version.
Sorry for my english ;)

**Comment by msaniscalchi** [comment]
Hello, thanks for the report! We're aware of the issue and are intentionally using an older version of oauth2client at this time due to an internal issue. We intend to update to the current version once this is resolved.

For the short term, if you need to also use the newer version of oauth2client for other projects, the easiest option is to use VMs to keep them separate. Alternatively, you could install both versions of oauth2client under different names, but you would need to patch at least one of the libraries to ensure that the correct version is used.

We'll close this bug when the issue has been resolved.

**Comment by josele86** [comment]
Thanks for the reply and for the solutions.
We can´t use VMs because is the same app use both libraries.
The solutions of patch is so difficult because we use ansible for the deployment and pip update automatly the packages.
Our solutions now is use the old packages until you can fix the bug and I'm glad to hear you already knew it.

**Comment by tym-oao** [comment]
Big +1 on this. As a member of [OAO](https://github.com/OAODEV), we have several ETL routines that pull from DFP reporting service and save results to Google Cloud Storage. LIke @josele86, the suggested workarounds are no good because of automated deployments and because obviously we require using both `googleads` and `google-api-python-client` simultaneously.

**Comment by tym-oao** [comment]
Any update on this issue?

**Comment by msaniscalchi** [comment]
We've been in communication with the oauth2client project internally and are working towards a solution.

That said, a fix to use the latest version of oauth2client is unlikely to happen in the near future (scale: weeks) because of a non-trivial amount of work that will need to be done outside of this repository in order to make it happen.

**Comment by daveFNbuck** [comment]
The issue was closed a week ago, but it doesn't seem to have been fixed yet. Any update on whether it'll be done soon?

**Comment by msaniscalchi** [comment]
Hello,

A duplicate issue was closed over a week ago; however, this has remained open because the issue hasn't been resolved yet. I can say that this is our highest priority issue at this time, but the fix is mostly dependent on work being done outside of this library. The work required for this library would take a few days at most to be released externally if that were not a factor.

While the core issue is much closer to a resolution now than it was at the time of my last update, I do not yet have a solid estimate on when it will happen.

**Comment by daveFNbuck** [comment]
Ah, my mistake. Thanks for the update!

**Comment by henryrizzi** [comment]
test comment

**Comment by henryrizzi** [comment]
Just wanted to leave a note here for @josele86 and others that, although at the moment `googleads` remains pinned to `oauth2client==1.5.2` it is possible as of the latest `google-api-python-client` to work around the issue of mutually incompatible oauth2client installations between the two libraries. Although google-api-python-client requires the latest oauth2client by default, it is backwards-compatible with 1.5.2. For the workaround, you just have to be careful to install googleads with pip _after_ google-api-python-client, so you end up with 1.5.2 instead of a newer version.

**Comment by dirkjonker** [comment]
@henryrizzi "being careful" is not a proper solution. For example, we use pip-tools for dependency checking and that obviously fails. Even if we work around the dependency checker, we do automatic builds and the order of installation of dependencies is not guaranteed.

**Comment by IamGianluca** [comment]
I've bumped into the same problem and found that fixing the version of `google-api-python-client` to v1.5.2 solves the dependency version issue. To be fair, even running with `google-api-python-client` v1.5.5 and `googleads` v4.7.0 was working fine, but was throwing warnings.

**Comment by dm03514** [comment]
Bump, do you have an updated timeline on this happening?

**Comment by msaniscalchi** [comment]
I made the changes necessary for this library to upgrade the oauth2client version to 3.0.0 (and now 4.0.0) quite some time ago, but I am not able to release it until an internal issue affecting other internal projects is resolved. Although that issue is actively being worked on, I can only say that we're realistically still looking at a time range of weeks to months.

If you really need to upgrade to a more recent version, it might make sense to create your own subclass of [`GoogleOAuth2Client`](https://github.com/googleads/googleads-python-lib/blob/master/googleads/oauth2.py#L60) and use that to instantiate a client.

**Comment by katsar0v** [comment]
This is an issue almost 1 year old... shame that this is a Google library...

**Comment by katsar0v** [comment]
How do I use this library together with the other Python libraries for Analytics and Search Console API??

**Comment by msaniscalchi** [comment]
That's a fair question. If you look to my earlier comment, one option I suggested is to create a subclass of GoogleOAuth2Client that is compatible with the version of oauth2client that you intend to use.

Another option might be to use something like [virtualenv](https://virtualenv.pypa.io/en/stable/).

**Comment by ajrheaume** [comment]
I'm having the same issue : I need version 1.5.2 of oauth2client to build the dataproc v1 API service and version 4.1.2 to build the analytics v3 API service. The last comment here is 8 months old, any news?
