### ISSUE TITLE
Timeout not defaulting to socket default timeout

### ISSUE THREAD

**Issue by zschneider** [googleads/googleads-python-lib#137]
Hello,

I've noticed an issue wherein we retry a LineItemStatus update after a 60 minute timeout and potentially revert changes made during that 60 minutes.

I'd like to decrease this timeout for our inline API calls to prevent this issue.

I see in your help section (https://github.com/googleads/googleads-python-lib#timeout-tips) that the timeout defaults to the socket default timeout if we use socket.setdefaultimeout() to set a system timeout.

However, in dfp.DfpClient.GetService I see a new suds client being created with a hard-coded 3600 second timeout value. Deeper in the suds library (suds.transport.http.HttpTransport.u2open), the timeout hard-coded in the client is set via socket.setdefaultimeout(), which overwrites any default value we manually entered in our code.

Please advise, and thanks for your time,

Zach

**Comment by nicholaschen** [comment]
So *generally* the SSL timeout we see in our libraries occur when downloading reports i.e. this is actually not bound by Suds or any of our service calls, but rather in failing to grab the requisite chunks of data when downloading the data files. The service libraries are constructed with a suds timeout of 3600s simply because we're upper-bounding the lifetime of an access-token. I suppose you could change that value to something that's more applicable.

This actually makes me wonder how it's not overriding the system socket setting every time a service is constructed (which it's clearly not), but at least the above should answer your question about reducing that 60 min timeout.

I am somewhat curious how you're using LineItem.Status to make changes - but this wouldn't be a client library question, so if you want to ask on the [forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api), please do clarify!

**Comment by nicholaschen** [comment]
Heya Zach,

I think if there's follow-up needed, please let us know on the forums! I'll close this out (feel free to reopen if there's further client lib specific questions)
