### ISSUE TITLE
How to create ImageAd?

### ISSUE THREAD

**Issue by heramerom** [googleads/googleads-python-lib#147]
I use the example `upload_image.py`
catch error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

if, I change `open(image_filename, 'r')` to `open(image_filename, 'rb')`
I got error:

```
suds.WebFault: Server raised fault: 'Unmarshalling Error: cvc-datatype-valid.1.2.1: 'b'/9j/4AAQSkZJRgABA...
```

so what is the right way to _upload image_ or create _ImageAd_

My python version is `python 3.5.2` and system is `ubuntu 16.04` and image is download from `http://goo.gl/9JmyKk`

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! It looks like this example was a casualty of the 2to3 conversion process. First off, you're correct that `open(image_filename, 'r')` should be changed to `open(image_filename, 'rb')`. That isn't enough though, it seems that the base64 encoded image data also needs to be decoded as well in Python 3.

In order to resolve the issue, modify `image_data = base64.encodestring(image_handle.read())` to `base64.encodestring(image_handle.read()).decode('utf-8')`.

Regards,
Mark Saniscalchi
