### ISSUE TITLE
ReportService.getSavedQueriesByStatement  returning isCompatibleWithApiVersion = False

### ISSUE THREAD

**Issue by abh1sh2k** [googleads/googleads-python-lib#153]
I have created few queries on https://www.google.com/dfp/ with my account . I am able to create report for those queries but when I am running this example it is returning following response : -
(SavedQueryPage){
   totalResultSetSize = 1
   startIndex = 0
   results[] = 
      (SavedQuery){
         id = XXXXX
         name = "Schedule_daily_queries_dont_delete"
         isCompatibleWithApiVersion = False
      },
 }

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! Can you clarify what example you're specifically referring to? Based on what I'm seeing, it looks like it could be a potentially valid response--i.e. there is one SavedQuery being returned in the response. What is it you're expecting to see instead?

**Comment by christopherseeley** [comment]
There are a number of columns, dimensions, and filters that aren't supported in the API. You can try cross checking the UI query with the API reference documentation and removing the unsupported attributes:
https://developers.google.com/doubleclick-publishers/docs/reference/v201608/ReportService.ReportQuery

**Comment by abh1sh2k** [comment]
Thanks  all for the  reply dimension which I am using currently are Country , Creative size , Date ( as shown on ui ) .the metrics which I am using Total impressions,Total clicks,Total CPM and CPC revenue ,Total average eCPM ,Total CTR,Ad server impressions,Ad server clicks,Ad server average eCPM ,Ad server CTR,Ad server CPM and CPC revenue ,Ad server impressions ,Ad server clicks ,Ad server revenue ,Ad Exchange impressions,Ad Exchange clicks,Ad Exchange CTR,Ad Exchange revenue ,Ad Exchange average eCPM ,Ad Exchange impressions ,Ad Exchange clicks ,Ad Exchange revenue  .

Report type which I am using is historical . the code run fine for date range ( yesterday ) but don't work when i choose some other date range .

**Comment by christopherseeley** [comment]
Thanks for the info. The date range also needs to be converted into API terms, so you may be using an unsupported value there:
https://developers.google.com/doubleclick-publishers/docs/reference/v201608/ReportService.ReportQuery#daterangetype

Alternatively, you can use yesterday in the UI query and then change the date range in the ReportQuery object that is returned in the API.

In the future, for questions about the DFP API (rather than the python client library itself) please use our [developer forums](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api). Thanks!
