### ISSUE TITLE
AD_EXCHANGE_* return ReportError.COLUMN_VIEW_NOT_ALLOWED

### ISSUE THREAD

**Issue by surfeurX** [googleads/googleads-python-lib#155]
Hi, 

It seems like there is an issue with the AD_EXCHANGE_* columns https://developers.google.com/doubleclick-publishers/docs/reference/v201608/ReportService.ReportQuery#columns. The returned response looks like:

`Failure response:
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Header>
      <ResponseHeader xmlns="https://www.google.com/apis/ads/publisher/v201608">
         <requestId>76f46fee749ff04180f0dd5fed6c9677</requestId>
         <responseTime>266</responseTime>
      </ResponseHeader>
   </soap:Header>
   <soap:Body>
      <soap:Fault>
         <faultcode>soap:Server</faultcode>
         <faultstring>[ReportError.COLUMN_VIEW_NOT_ALLOWED @ columns; trigger:&apos;AD_EXCHANGE_ECPM, AD_EXCHANGE_ESTIMATED_REVENUE&apos;]</faultstring>
         <detail>
            <ApiExceptionFault xmlns="https://www.google.com/apis/ads/publisher/v201608">
               <message>[ReportError.COLUMN_VIEW_NOT_ALLOWED @ columns; trigger:&apos;AD_EXCHANGE_ECPM, AD_EXCHANGE_ESTIMATED_REVENUE&apos;]</message>
               <errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ReportError">
                  <fieldPath>columns</fieldPath>
                  <trigger>AD_EXCHANGE_ECPM, AD_EXCHANGE_ESTIMATED_REVENUE</trigger>
                  <errorString>ReportError.COLUMN_VIEW_NOT_ALLOWED</errorString>
                  <reason>COLUMN_VIEW_NOT_ALLOWED</reason>
               </errors>
            </ApiExceptionFault>
         </detail>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
`

Thank you

**Comment by christopherseeley** [comment]
The columns with the AD_EXCHANGE prefix are experimental and only work on certain networks with specific Ad Exchange configurations. You probably want to use the columns prefixed with DYNAMIC_ALLOCATION instead. It may be easier to create the query in the UI first and then retrieve it using getSavedQueriesByStatement.

In the future, for questions about the DFP API (rather than the python client library itself) please use our [developer forums](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api). Thanks!

**Comment by surfeurX** [comment]
Thank you very much @christopherseeley
