### ISSUE TITLE
enum values header flag doesn't work as expected

### ISSUE THREAD

**Issue by VikramTiwari** [googleads/googleads-python-lib#160]
While downloading reports from Python SDK, we get the ability to pass various headers. One of them being `use_raw_enum_values` which makes sure that the column headers of the downloaded report have the enum values rather than UI display values as headers.

Current Python SDK is not behaving as expected. Every other header except `use_raw_enum_values`, works as desired.

Details:
SDK Version: v201609
Query:
`report_downloader.DownloadReportWithAwql(
          report_query, 'CSV', output_file, skip_report_header=True,
          skip_column_header=False, skip_report_summary=True, use_raw_enum_values=True, include_zero_impressions=False)`

Am I missing something?

Original discussion here: https://groups.google.com/forum/#!topic/adwords-api/iGQTt0Kpx84

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! I can see that the header is being sent in the request, but I can verify that it doesn't appear to be having the desired effect. I'm not so certain that this is actually an issue with this library, so I'll check in with the AdWords team to see if this might be an issue with the API itself.

Regards,
Mark

**Comment by msaniscalchi** [comment]
On further review with the AdWords team, I realized that my earlier verification of this issue was incorrect. I can't reproduce the behavior you're describing. When setting `use_raw_enum_values` to `True`, the downloaded report correctly uses enum rather than display values.

If you're still experiencing this issue, please attach an example of the output you're seeing with `use_raw_enum_values` set to `True`.

**Comment by VikramTiwari** [comment]
This is the header from one of the samples reports.

`Day,Ad group ID,Ad group,Campaign ID,Campaign,Network,Cost,Impressions,Clicks,Conversions`

I was expecting all caps and spaces replaced by _ (underscores).

**Comment by msaniscalchi** [comment]
Thanks for the additional information. That's actually not what the use_raw_enum_values header does; it doesn't modify the column headers. Instead, it will modify the content found in the rows to use enum values rather than display values.

For example, in a Criteria Performance Report, the `Criteria Type` column might have `KEYWORD` if use_raw_enum_values were set to `True` or `Keyword` if it were not included or set to `False`.

**Comment by VikramTiwari** [comment]
Ah! Documentation could be improved. It's a bit confusing.
