### ISSUE TITLE
Python script run directly but not from hapi.js using python-shell 

### ISSUE THREAD

**Issue by shubsaini09** [googleads/googleads-python-lib#170]
If i call the script.py directly in my terminal then it works but when i call it from my controller.js then it does not. A simple program works in the script.py but my below code does not. My forever just breaks but does not show any error. I have tried it with options, sending data using events like on, message but nothing works. Can anyone help why it does not work? what should be done to make it work?

`controller.js`
```
var PythonShell = require('python-shell');
PythonShell.defaultOptions = { scriptPath: './server/python/' };

exports.adwords =  {
  handler: function(request, reply){
    PythonShell.run('script.py', function (err, res) {
      if (err) throw err;
      reply(res); 
    });
});
```
`script.py`
```
import logging
import os
import sys, json
import csv
from googleads import adwords

logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.transport').setLevel(logging.DEBUG)


def main(client):
   report_downloader = client.GetReportDownloader(version='v201609')

report = {
  'reportName': 'LAST_7_DAYS AD_PERFORMANCE_REPORT',
  'dateRangeType': 'LAST_7_DAYS',
  'reportType': 'AD_PERFORMANCE_REPORT',
  'downloadFormat': 'CSV',
  'selector': {
      'fields': ['CallOnlyPhoneNumber', 'Cost']
  }
}

file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),"report.csv")
f = open(file_path,'wb')
f.write(report_downloader.DownloadReportAsString(report, skip_report_summary=True))
f.close()

with open(file_path, 'rb') as f:
  f.next()
  reader = csv.DictReader(f)
  data = dict()

  for row in reader:
    number = row['Call-only ad phone number'].replace("-", "")
    number = number.strip()
    if number:
      if number in data:
        data[number] += int(row['Cost'])
      else:
        data[number] = int(row['Cost'])

print data
f.close()

if __name__ == '__main__':
  adwords_client = adwords.AdWordsClient.LoadFromStorage()
  adwords_client.SetClientCustomerId('111-111-1111') 
  main(adwords_client)
```

**Comment by msaniscalchi** [comment]
Hello Shubham,

I'm pretty confident that this is not an issue with the library, but rather that it is related to your execution via your `controller.js` script. Due to that, I will be closing this issue because it is out of scope for this issue tracker.

That said, my informed guess for this particular issue would be that the Python shell being invoked by `controller.js` does not use the Python path you might expect. It's possible that it doesn't detect the googleads installation (or that of any dependencies), and is failing to import what `script.py` needs to work.

Regards,
Mark
