### ISSUE TITLE
1hour suds request timeout?

### ISSUE THREAD

**Issue by calvinfo** [googleads/googleads-python-lib#183]
Hey there,

We've got a small subset of Adwords requests which seem to hang sometimes, and we have a suspicion it is coming from the 1 hour timeout set on the request:

https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L380-L390

Is there any way you can add this as an option to make it configurable? We could manually patch it but we'd prefer to use a documented API here.

**Comment by msaniscalchi** [comment]
Hello,

We intentionally set this to one hour by default a while back to better handle large reports that would otherwise be truncated in certain scenarios, such as when the access token expires. If you're interested in changing the default timeout, you can do so via something like the following:

```
import socket
socket.setdefaulttimeout(timeout)
```

Regards,
Mark

**Comment by calvinfo** [comment]
Got it, I realized I missed that in the Readme, thanks!
