### ISSUE TITLE
error code 400 on downloadReport

### ISSUE THREAD

**Issue by Olmer1st** [googleads/googleads-python-lib#190]
Hi, when trying to download any report with zero_impressions and some field not support it the error raised:
'AdWords report download failed with HTTP status code: 400'

But before was details - which field are wrong.
Now no exception details, is it the bug?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! So if I'm understanding correctly, you're setting the `include_zero_impressions` keyword argument of the `ReportDownloader` to `True`, and the result is an HTTP 400 error response?

I'm not able to reproduce this reported issue; e.g. I modified the selector if the [download_criteria_report_with_selector.py](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201702/reporting/download_criteria_report_with_selector.py) sample and set `include_zero_impressions` to `True`. I still received the expected error message, in my case being:

```
googleads.errors.AdWordsReportBadRequestError: Type: ReportDefinitionError.INVALID_FIELD_NAME_FOR_REPORT
Trigger: Cost2
Field Path: None
```

Can you provide a snippet of code that you can use to reproduce the issue? Likewise, some details on your version of Python and the googleads library may be helpful.

Regards,
Mark

**Comment by Olmer1st** [comment]
Hi,

Please try the code below. 
`import logging
import sys
from googleads import adwords

logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.transport').setLevel(logging.DEBUG)


def main(client):
  report_downloader = client.GetReportDownloader(version='v201702')
  report = {
      'reportName': 'Last 7 days SHOPPING_PERFORMANCE_REPORT',
      'dateRangeType': 'LAST_7_DAYS',
      'reportType': 'SHOPPING_PERFORMANCE_REPORT',
      'downloadFormat': 'CSV',
      'selector': {
          'fields': ['CampaignId', 'CampaignName', 'AdGroupId', 'AdGroupName', 'OfferId', 
                     'Brand', 'Impressions', 'Clicks', 'Cost']
      }
  }
  report_downloader.DownloadReport(
      report, sys.stdout, skip_report_header=False, skip_column_header=False,
      skip_report_summary=False, include_zero_impressions=True)
if __name__ == '__main__':
  adwords_client = adwords.AdWordsClient.LoadFromStorage()
  main(adwords_client)`

**Comment by msaniscalchi** [comment]
Thanks for the additional information.

I ran the provided code in a similar environment. I do receive an error response when running the given code, but I receive the following:

```
googleads.errors.AdWordsReportBadRequestError: Type: ReportDownloadError.ZERO_IMPRESSIONS_REQUEST_NOT_SUPPORTED
Trigger: includeZeroImpressions is not supported for this request
Field Path: None
```

As the error response indicates, the request is failing because includeZeroImpressions is not supported for the given report and fields. I suggest reaching out to the [AdWords API Support forum](https://groups.google.com/forum/#!forum/adwords-api) if you need help constructing a report using this header.

I'm a bit puzzled on why our error responses seem to differ, but I can at least confirm that [several of the fields you specify for the Shopping Performance Report do not support zero impressions](https://developers.google.com/adwords/api/docs/appendix/reports/shopping-performance-report). Removing the incompatible fields or the header should resolve the issue.

**Comment by Olmer1st** [comment]
Hi,

Yes. I know about zero-impressions and which fields support it. I juzt informed about the problematic exception.
And as i understand you can reproduce the problem by replacing CSV to GZIPPED_CSV.

Thanks

**Comment by msaniscalchi** [comment]
I modified the code you provided to download a report in the `GZIPPED_CSV` format:

```
import logging
import sys
from googleads import adwords

logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.transport').setLevel(logging.DEBUG)


def main(client):
  report_downloader = client.GetReportDownloader(version='v201607')
  report = {
      'reportName': 'Last 7 days SHOPPING_PERFORMANCE_REPORT',
      'dateRangeType': 'LAST_7_DAYS',
      'reportType': 'SHOPPING_PERFORMANCE_REPORT',
      'downloadFormat': 'GZIPPED_CSV',
      'selector': {
          'fields': ['CampaignId', 'CampaignName', 'AdGroupId', 'AdGroupName', 'OfferId', 
                     'Brand', 'Impressions', 'Clicks', 'Cost']
      }
  }

  with open('test_download_report_result.txt', 'wb') as handler:
    report_downloader.DownloadReport(
        report, handler, skip_report_header=False, skip_column_header=False,
        skip_report_summary=False, include_zero_impressions=True)


if __name__ == '__main__':
  adwords_client = adwords.AdWordsClient.LoadFromStorage()
  main(adwords_client)
```

Running this still produces an error response producing the following stracktrace:

```
Traceback (most recent call last):
  File "test_download_report.py", line 29, in <module>
    main(adwords_client)
  File "test_download_report.py", line 24, in main
    skip_report_summary=False, include_zero_impressions=True)
  File "build/bdist.linux-x86_64/egg/googleads/common.py", line 503, in Wrapper
  File "build/bdist.linux-x86_64/egg/googleads/adwords.py", line 1271, in DownloadReport
  File "build/bdist.linux-x86_64/egg/googleads/adwords.py", line 1541, in _DownloadReport
  File "build/bdist.linux-x86_64/egg/googleads/adwords.py", line 1594, in _DownloadReportAsStream
googleads.errors.AdWordsReportBadRequestError: Type: ReportDownloadError.ZERO_IMPRESSIONS_REQUEST_NOT_SUPPORTED
Trigger: includeZeroImpressions is not supported for this request
Field Path: None
```

This is the expected error response, indicating that `includeZeroImpressions` is not supported. I even tried a number of unusual local modifications that I expected might produce an HTTP 400 error--e.g. modifying the contents of the generated request body. I'm not able to reproduce the unhelpful error response, an `AdWordsBadRequestError` is raised, and error details are provided. The `AdWordsReportError` you're seeing is a more generic error that generally indicates something went wrong server-side. It might be worth examining the `content` of the exception, as that may contain additional clues.

If this is consistent for you, I suggest reporting it to the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api). I do not think the underlying cause is specific to this library.

**Comment by Olmer1st** [comment]
Ok. Ignore it.... you can close the issue.
