### ISSUE TITLE
Problem with GEO_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by oleg-albert-ai** [googleads/googleads-python-lib#206]
Field CityCriteriaId returns entities that are not cities

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! This sounds like you might be referring to an API issue rather than an issue with the library itself. For issues with the API, reach out on the [AdWords Support Forum](https://groups.google.com/forum/#!forum/adwords-api). I'll close this for now, but feel free to re-open if you have reason to believe that this library is related to this issue.
