### ISSUE TITLE
Adding/updating custom criteria for line items

### ISSUE THREAD

**Issue by haldunanil** [googleads/googleads-python-lib#212]
I'm trying update/assign custom criteria to a line item, but I can't seem to find any documentation on the topic. I use Python 3.5. I've tried the following, but have gotten various errors:

Below, you'll see a reference to "children" which is the following:
`children = [{'keyId': '363254', 'valueIds': ['168698025614'], 'operator': 'IS'}, {'keyId': '388694', 'valueIds': ['95443548014'], 'operator': 'IS'}]`

# First attempt
    line_item['targeting']['customTargeting']['children'][0]['children'] = children

The error here was: `Type not found: 'keyId'`

# Highest level update:
    line_item.targeting.customTargeting = {
        'logicalOperator': "OR",
        'children': [
            {
                'children': children,
                'logicalOperator': 'AND'
            }
        ]
    }

The error here is: `Type not found: 'children'`

**Comment by msaniscalchi** [comment]
Hello,

It seems like your question is more of a product-specific question about DFP rather than an issue with this library. We recommend that you direct questions you may have about this to the [DFP Support Forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api), as this issue tracker is strictly intended for issues with the library.

Regards,
Mark
