### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

### ISSUE THREAD

**Issue by julgq** [googleads/googleads-python-lib#213]
I have this code and, I have this result:
**urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>**

`import logging
import time
from googleads import adwords

logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.transport').setLevel(logging.DEBUG)

PAGE_SIZE = 100

def main(client):
  # Initialize appropriate service.
  campaign_service = client.GetService('CampaignService', version='v201705')

  # Construct selector and get all campaigns.
  offset = 0
  selector = {
      'fields': ['Id', 'Name', 'Status'],
      'paging': {
          'startIndex': str(offset),
          'numberResults': str(PAGE_SIZE)
      }
  }

  more_pages = True
  while more_pages:
    page = campaign_service.get(selector)

    # Display results.
    if 'entries' in page:
      for campaign in page['entries']:
        print ('Campaign with id \'%s\', name \'%s\', and status \'%s\' was '
               'found.' % (campaign['id'], campaign['name'],
                           campaign['status']))
    else:
      print ('No campaigns were found.')
    offset += PAGE_SIZE
    selector['paging']['startIndex'] = str(offset)
    more_pages = offset < int(page['totalNumEntries'])
    time.sleep(1)

if __name__ == '__main__':
  adwords_client = adwords.AdWordsClient.LoadFromStorage('googleads.yaml')
  main(adwords_client)

`

**Comment by msaniscalchi** [comment]
Hello,

We see [reports like this](https://github.com/googleads/googleads-python-lib/issues/211) every so often. It seems to be an environment issue rather than one strictly related to this library, although it has been difficult to pinpoint a precise cause.

For starters, I would recommend doing a fresh install of this library and its dependencies. If you still see this issue afterwards, try doing a fresh install of Python.

Regards,
Mark

**Comment by msaniscalchi** [comment]
Closing because I'm assuming the issue was resolved. Feel free to reopen otherwise.
