### ISSUE TITLE
get_keyword_ideas.py generates unexpected output

### ISSUE THREAD

**Issue by Quantzz** [googleads/googleads-python-lib#216]
When trying to run the get_keyword_ideas.py code i get the following as the output

    Keyword with 'space cruise 98e351d2' text and average monthly search volume '4623012' was found 
    with Products and Services categories: [33, 27, 10628, 14].
    Keyword with 'red herring 7043808' text and average monthly search volume '5310299' was found 
    with Products and Services categories: [41, 65, 10628, 47].
    Keyword with 'red herring 9581649e' text and average monthly search volume '3857696' was found 
    with Products and Services categories: [24, 3, 10628, 14].

Is this correct? If so how should all these numbers i.e "7043808" and 'red herring' be intepreted?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for reaching out. This is more of an API question rather than an issue with this library--if you have questions like this in the future, we recommend you ask it via the [AdWords Support Forum](https://groups.google.com/forum/#!forum/adwords-api) rather than this client library issue tracker. We generally only respond to reported issues that are directly related to the library here.

Regarding your question, that particular sample is using the [TargetingIdeaService](https://devsite.googleplex.com/adwords/api/docs/reference/v201705/TargetingIdeaService), which is used to generate Keyword ideas based on the provided selector. The printed portion of the `get` response shows the keyword text and the suggested search volume for that keyword. **It sounds like you're probably running this sample with a test account, which will not return a result with real data. In order to get actual recommendations, you would need to use a non-test account.**

Regards,
Mark Saniscalchi
