### ISSUE TITLE
Let v201708 sample script "add_responsive_display_ad.py" compatible with Python 3.x

### ISSUE THREAD

**Issue by JamesHuang123** [googleads/googleads-python-lib#224]
The v201708 sample script ["add_responsive_display_ad.py"](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201708/advanced_operations/add_responsive_display_ad.py) uses package urllib2 to fetch internet image resource. However urllib2 is not available in Python 3.x and is replaced with urllib.request, but when I used urllib.request for this line and execute the full code 

opener = urllib.request.build_opener(*client.proxy_config.GetHandlers())

The program return an message 'Unmarshalling Error: cvc-datatype-valid.1.2.1: 'b'/9j/4AAQSkZJRgABAQAAAQAB...........(a long encoded string)...' is not a valid value for 'base64Binary'.

We tried switching back to Python 2.x and run the code with urllib2, then the program works perfectly, but not with urllib.request under Python 3.x environment. So it seems this sample code is not compatible with Python 3.x which urllib2 is not available. Please help update the library to be compatible with both Python 2.x and Python 3.x if possible.

many thanks,

**Comment by msaniscalchi** [comment]
Hello James, thanks for the report!

Sorry to hear that the sample isn't working for Python 3 users. I'll take a look.

**Comment by msaniscalchi** [comment]
Here's the logs demonstrating what is sent correctly in [Python 2](https://pastebin.com/qZ7gV741) and incorrectly in [Python 3](https://pastebin.com/WXYqeHVT). Did you spot the difference?

It looks like the underlying issue is that bytes don't cleanly print out their contents as the equivalent str does in Python 2. To get an idea of the issue, try a trivial exercise in your Python interpreter window:

```
>>> print('hello')
hello
>>> print(b'hello')
b'hello'
```

Look closer at the Python 3 logs and you'll see that the base64 encoded data is surrounded by `b&apos;` and `&apos;`. Or in other words, `b''`. The suds library accepts the bytes object and simply inserts it into the generated SOAP request without any complaint.

As a work-around, you can make the following modification:
```
  image_data = base64.b64encode(opener.open(url).read()).decode('utf-8')
```

This is more of an issue with the Python 3 examples after 2to3 conversion rather than an issue with the library itself. I'll try to sneak in a fix for these examples in the next release.

**Comment by JamesHuang123** [comment]
Hi Msaniscalchi,

Thank you for your update. I took a look at the log and tried your fix. The script is working perfectly within Python 3 environment now. Appreciate your help in fixing the issue.

Regards,
James
