### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by oseemann** [googleads/googleads-python-lib#23]
Hi!

There are few issues when migrating to this lib that are currently not addressed. Mainly two things:
- Lack of error exceptions. The user application must parse the error objects itself and also establish its own exception hierarchy. It cannot rely on approriate exceptions being raised by the client lib. The previous lib (adspygoogle) partly did this, however a lot of clients would benefit when the error-string -> exception mapping would happen in the lib.
- OAuth error handling is missing. When the attempt to retrieve an access token from a refresh token fails then the lib currently silently omits the Authorization header, leading to LOGIN_COOKIE_REQUIRED api errors. OAuth error handling should be extended. Additionally it may be helpful to also allow giving access tokens to the client in order to enable reusing access tokens within their life time.

Is anybody currently working on a new set of related feature for the lib or should we start submitting patches?

**Comment by msaniscalchi** [comment]
Hello.

This is a very old issue. At this point, I do not expect migration issues to still be a major concern. The library was very different when this issue was filed. I am closing this issue for the following reasons:

1. For client-specific errors, error exceptions are raised. I think it is appropriate for us to allow exceptions from dependency libraries to bubble up, rather than wrapping them in our own customized exception classes.

1. We switched from oauthlib to oauth2client (still on 1.4.12...) a long time back, and in doing so, your request here was fulfilled. We raise an AccessTokenRefreshError if the refresh fails.

If you feel there is still room for improvement that hasn't yet been addressed, please open a new issue.

Regards,
Mark
