### ISSUE TITLE
Not compatible with Python 3

### ISSUE THREAD

**Issue by Kyushi** [googleads/googleads-python-lib#231]
Brackets are missing for the print statement for compatibility with Python 3
https://github.com/googleads/googleads-python-lib/blob/18c083ca1c7657dd13c8f67c120ad550d5964dd5/examples/adwords/authentication/generate_refresh_token.py#L58

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! You're correct that this sample is not compatible with Python 3, but that is actually expected behavior for the samples that are hosted directly on GitHub. Please see our [releases](https://github.com/googleads/googleads-python-lib/releases) page to download samples for Python 3.

Regards,
Mark

**Comment by Kyushi** [comment]
Oh, thanks for the clarification. Will head right over to the releases.
