### ISSUE TITLE
adwords module takes up a lot of CPU power

### ISSUE THREAD

**Issue by Quantzz** [googleads/googleads-python-lib#238]
Hi, 
I'm trying to deploy a web app that includes the AdWords module, the current server is rather small, however 1 call to the adwords api takes up ~90% of CPU power, using the code example for targeting ideas. Is this normal, or am i missing some configuration of some sort?

**Comment by msaniscalchi** [comment]
We haven't deeply investigated web app performance because it's a very niche use-case, so it's difficult to provide specific data on what is "normal" for that environment. I can say though that the most likely cause relates to the [Cache](https://bitbucket.org/jurko/suds/src/0fcfff1ea149397bfa23c7537a0ae2ac300e9564/suds/cache.py?at=release-0.6&fileviewer=file-view-default) or lack thereof. This can be specified when [initializing an AdWordsClient instance](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L363).

One thing to keep in mind is that this library is dynamically generated; i.e. assuming that the cache is disabled, for every API call you make, you are downloading and parsing a WSDL to create the service objects. Even if the cache is enabled, you are still downloading and parsing a WSDL on the first API call to a particular service. Of course, the cache itself does need to be refreshed every so often, which means you will again re-download and parse the WSDL to do that. I'm not sure what, if any, caching mechanism you are using for your web app, but that is one plausible cause for worse performance.

Another possibility that I would expect to have a lesser impact is logging. If it is enabled, there will be additional processing done to handle the logs and redact certain sensitive information.

Regards,
Mark

**Comment by msaniscalchi** [comment]
As an update, we are considering migrating to zeeps for our SOAP client library in a future release, which we anticipate would have a significant positive impact on the performance of the library.

For the moment though, I don't think there is anything actionable I can recommend outside of my earlier suggestions. I'll be closing this issue for now, but feel free to reopen if there's more I can help with on this topic.
