### ISSUE TITLE
Python3.6 encoding issue

### ISSUE THREAD

**Issue by geobol** [googleads/googleads-python-lib#265]
Hi, I'm trying to use the API on Windows, running Python 3.6.
I have tried different ways to encode/decode to UTF-8 but all the same, I'm getting this error:

> Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.

When I run this I get UTF-8 as a result.
```
import sys; 
print(sys.getdefaultencoding())
```

Can you tell me, if there is a way around this? Or how to solve this issue?

Thank you

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! I can see how this might not be super clear--the warning you're seeing is referring to your OS's locale's encoding. The reason this warning was added was because users without a locale using utf-8 had frequently reported that they were having some sort of encoding issue when the underlying issue was that their OS could not actually display certain characters because of their configuration.

This warning is just a harmless reminder that you're running on an environment that may not be able to display certain unicode characters. You can stop the nagging by configuring your OS to use a locale with utf-8 encoding.

Regards,
Mark
