### ISSUE TITLE
Problems in ADGROUP_PERFORMANCE_REPORT with different googleads versions, same API version

### ISSUE THREAD

**Issue by jonathan-scholbach** [googleads/googleads-python-lib#277]
I use the AdWords API version `v201710`

When requesting an `ADGROUP_PERFORMANCE_REPORT` with `googleads=11.0.1` I get 

> WARNING:googleads.adwords.report_downloader:Request Summary: {'clientCustomerId': '...', 'includeZeroImpressions': 'False', 'server': 'adwords.google.com', 'skipColumnHeader': 'True', 'skipReportHeader': 'True', 'skipReportSummary': 'True', 'isError': True, 'errorMessage': '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><reportDownloadError><ApiError><type>ReportDownloadError.INVALID_REPORT_DEFINITION_XML</type><trigger>Invalid ReportDefinition Xml: DateError.INVALID_STRING_DATE @ </trigger><fieldPath></fieldPath></ApiError></reportDownloadError>'}

The result I get from the report is `None`.

However, using the same report definition, but with `googleads==10.0.0` everything works fine - I get no warning and the result is the actual report.

How come? I cannot figure out, why I get an error when neither the report definition nor the API version is not changed.

**Comment by msaniscalchi** [comment]
Hello Jonathan,

Thanks for the report! It's plausible that the underlying cause is related to the change in default SOAP client that was introduced in 11.0.0. To troubleshoot, I'd suggest [switching the default SOAP client back to suds](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml#L124) to see if it resumes working as usual.

I think it'd also be helpful in this case to see a trivial case in code that can be used to reproduce.

Regards,
Mark
