### ISSUE TITLE
Import Module Error while using adwords library in AWS Lambda

### ISSUE THREAD

**Issue by lmishra92** [googleads/googleads-python-lib#279]
I am trying to connect to Googleads API from AWS Lambda in Python 3.6 runtime environment. My lambda function is unable to find the module `lxml.etree`. I have tried researching for it and I am unable to fix this issue. However when I run the code from localhost, there is no such error. What is the best way to resolve it ?

**Comment by grivescorbett** [comment]
Hello,

Thanks for writing in! I've done some searching and it looks like there is a bit of leg work to be done in order to use lxml on AWS lambda, and lxml is a dependency of our library. 

Please reference [this](https://stackoverflow.com/questions/36397171/aws-lambda-not-importing-lxml) StackOverflow thread and potentially [this](https://github.com/JFox/aws-lambda-lxml) open source project for more information.
