### ISSUE TITLE
UnicodeDecodeerror since upgrading googleads

### ISSUE THREAD

**Issue by samy20002000** [googleads/googleads-python-lib#307]
Hi, since upgrading the googleads library to googleads-12.2.0, I have a new error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte", it seems it cannot encode the p12 file.

Is there any way to solve that ? If i downgrade to previous version of googleads (5.0.0) the problem is solved but i can't use the recent classes (such as statementbuilder).

Thanks

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! I suspect the root cause of this issue is that support for (now-deprecated) P12 key files has been removed in favor of JSON key files. I'd recommend finding the cloud project you used to produce the Service Account and download a keyfile for that Service Account in JSON format.

Regards,
Mark

**Comment by samy20002000** [comment]
Thanks a lot I will test that !
