### ISSUE TITLE
Campaign settings in batch job result not containing dynamic search page feeds

### ISSUE THREAD

**Issue by sliu-walmart** [googleads/googleads-python-lib#308]
The 'pageFeed' key doesn't exist in the campaign settings returned in batch job results, while CampaignService.get works fine.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! So it sounds like you're creating a BatchJob that creates DynamicSearchAds and the result includes everything but the Campaign setting's PageFeeds?

Provided that this is restricted to one specific field as described, it sounds like an issue likely related to the API itself rather than this client library. I suggest reaching out on the [AdWords support forum](https://groups.google.com/forum/#!forum/adwords-api) to verify whether this is API behavior and whether it is intended.

Regards,
Mark

**Comment by sliu-walmart** [comment]
We're direct client library users instead of the API itself. So shouldn't we report any bugs found when using the library for you folks to investigate and escalate to the API layer if necessary? I suppose we shouldn't need to look into the client library code to figure out ourselves if a bug is caused by the library or something else.

**Comment by msaniscalchi** [comment]
> So shouldn't we report any bugs found when using the library for you folks to investigate and escalate to the API layer if necessary?

No, we don't investigate API issues on this issue tracker. I'd actually suggest the opposite; if you're not sure if the underlying issue is related to the API, start at the API support forum and escalate to the specific library's issue tracker if it is found to be an issue directly related to that library. The reasoning for this is that if the underlying API has an issue, it's likely not possible for us to resolve your issue at the client library level--e.g. it wouldn't be possible for us to add a field that doesn't exist in the API response.

In hindsight though, there is one quick way to determine whether this is an API or client library issue. Assuming that you're using `ParseResponse`, you should be passing in the response XML. Does the response XML contain this field? If not, then it is definitely related to the API rather than this client library.

Regards,
Mark

**Comment by sliu-walmart** [comment]
I think this is frustrating. Many times when we reach out to the API support team, we were told to create a ticket here, but now more and more often our requests are getting kicked back here... We wish Google to work like a team with us, instead of kicked us back and forth.

**Comment by sliu-walmart** [comment]
confirmed this is an issue with the API side.
