### ISSUE TITLE
Unrecognized version

### ISSUE THREAD

**Issue by dwujellyfish** [googleads/googleads-python-lib#312]
I went through the installed app authentication flow, edited the googleads.yaml file and finally was ready to run a test with the example file (get_report_fields.py)
Here are the lines I ran: 

`from googleads import adwords
adwords_client = adwords.AdWordsClient.LoadFromStorage()
adwords_client.GetService('ReportDefinitionService', version='v201806')
`
However the program does not seem to find the version 201806, here are the errors:
Traceback (most recent call last):
  File "/home/miniconda3/lib/python3.6/site-packages/googleads/adwords.py", line 433, in GetService
    version_service_mapping = _SERVICE_MAP[version][service_name]
KeyError: 'v201806'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/lib/python3.6/site-packages/googleads/adwords.py", line 442, in GetService
    msg_fmt % ('version', version, list(_SERVICE_MAP.keys())))
googleads.errors.GoogleAdsValueError: Unrecognized version for the AdWords API. Given: v201806 Supported: ['v201702', 'v201705', 'v201708', 'v201710']

I am suspect the versions of my googleads is not up to date.  If I change the version to 'v201710' for example, it would throw out a urllib.error.HTTPError: HTTP Error 404: Not Found error.

**Comment by msaniscalchi** [comment]
Hello,

I'm pretty confident that your suspicions are correct on this one; support for new versions of AdWords are added over time, as older versions are likewise removed. Support for AdWords v201806 was added in the [12.1.0 release](https://github.com/googleads/googleads-python-lib/releases/tag/12.1.0).

Can you verify which version of the library you're using? If it's lower than 12.1.0, you'll need to upgrade in order to access AdWords v201806.

Regards,
Mark

**Comment by dwujellyfish** [comment]
Yep problem solve after I ran: 
`pip install googleads --upgrade`
Thanks!!!
