### ISSUE TITLE
DataService API is giving zero results

### ISSUE THREAD

**Issue by ved93** [googleads/googleads-python-lib#318]
I am using below API to get bid simulations.
https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201806/optimization/get_keyword_bid_simulations.py

But my API calls giving zero results
Screenshot: 
![image](https://user-images.githubusercontent.com/8381908/44338426-813dd780-a49b-11e8-8ba8-1f1973d09075.png)

**Comment by msaniscalchi** [comment]
Hello,

I can reproduce with a freshly created Ad Group / Criterion, but I think that is likely the cause--e.g. see the Troubleshooting section of the [Bid Simulators Help Center article](https://support.google.com/google-ads/answer/2470105). A lack of data, such as for newly created Ad Groups / Keywords, may result in no estimates being returned.

As an FYI, I believe this sample is working as intended, but not returning anything because of the input AdGroup and Criterion. From a client library perspective, there's not much additional we can do to troubleshoot this issue, but I do recommend that you reach out to the [Google Ads Support Forum](https://groups.google.com/forum/#!forum/adwords-api) if you need help or have additional questions pertaining to bid simulators.

Regards,
Mark
