### ISSUE TITLE
Your default encoding, cp936, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.

### ISSUE THREAD

**Issue by yinliangc** [googleads/googleads-python-lib#319]
Your default encoding, cp936, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.

I will use your latest get_keyword_ideas.py，  Once I run it, I'm going to run it. I'm using version 3.6 of python, and windows,  and it's been around for a long time. Why can't it be solved yet

**Comment by msaniscalchi** [comment]
Hello,

Thanks for reaching out! The warning message you're reporting is not a bug; it's an intentional message we have built into the library to suggest that your locale settings may be problematic when working with this client library. That said, it will otherwise have no effect if you choose to continue using the same configuration.

The history behind this decision is that we received several reports of encoding / decoding related errors in the past, usually when users unexpectedly received utf-8 characters in the response for the first time. The underlying cause of these issues was largely related to their locale configuration, which was typically set to ascii. I am not very familiar with cp936 encoding, but provided that it only covers a limited subset of unicode characters as ascii does, I expect you would encounter similar issues when working with incompatible unicode characters.

If you want this warning to stop appearing when initializing the client library, I recommend changing your locale configuration. This process can differ depending on your platform; for Windows, you may want to read [this article](https://answers.microsoft.com/en-us/surface/forum/surfbook-surfaccess/how-to-change-system-locale-in-windows-10-the/d7826ef0-13cd-43ea-8e01-2846d813dfed).

Regards,
Mark
