### ISSUE TITLE
OperationAccessDenied.ADD_OPERATION_NOT_PERMITTED

### ISSUE THREAD

**Issue by Tahirhan** [googleads/googleads-python-lib#347]
Hi, i am trying to add campaign for testing. But when i execute the add_campaign.py code i get this error : 

`  campaigns = campaign_service.mutate(operations)
  File "/usr/local/lib/python3.5/dist-packages/googleads/common.py", line 1389, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: [OperationAccessDenied.ADD_OPERATION_NOT_PERMITTED @ operations[0], OperationAccessDenied.ADD_OPERATION_NOT_PERMITTED @ operations[1]]`

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! What you're seeing there is an API error response, which pretty strongly indicates that the underlying issue is related to the API as opposed to this library. The error suggests that the authorized user or specified client customer ID does not have permission to use the ADD operation. Digging deeper on this would be out of scope for us here, as this issue tracker is intended to resolve issues with this library.

For issues directly related to the API or your account rather than this library, you should reach out on the [AdWords / Google Ads API Support forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark
