### ISSUE TITLE
Generic error while calling service.files().get

### ISSUE THREAD

**Issue by datacubed** [googleads/googleads-python-lib#354]
I hope this is the correct place to flag this up. 
My below code runs to pull doubleclick api data
```
try:
	request = service.files().get(reportId=report_id, fileId=file_id)
	response = request.execute()
	break
except Exception as ex:
	print("Error getting report status:\n{0}".format(ex))	
```
Output:

> Error getting report status: 'NoneType' object has no attribute 'readline'

Not sure where this is specifically happening in the API lib. 
I call the above inside of a while loop, and after some time has passed, the report status is 'REPORT_AVAILABLE' - but I always get the above error at least once while waiting.

If I've misunderstood the how to use the API or if this is correct behaviour that is fine.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! This is a little vague in the sense that I don't see how you instantiated the client, or what service you're calling. These along with a stacktrace would go a long way towards determining an underlying cause.

The error output suggests that somewhere in the process of executing your request, an attempt was made to read from a `file` (or similar interface). It looks like it failed because the intended file-like object was actually set to `None`.

Regards,
Mark
