### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'auto: 600000'

### ISSUE THREAD

**Issue by kristen668** [googleads/googleads-python-lib#379]
I started to have this issue after migrating to API v201806. I'm wondering if there's any fix i can do? The only thing i did for migration is to replace v201802 with v201806 in my code.
Thank you very much!

**Comment by BenRKarl** [comment]
@kristen668 thanks for bringing this up! Can you share some details as to what request you're making? Also have you tried upgrading to `v201809`? `v201806` will be deprecated in a few weeks so it might be easier to skip to the newest version.

**Comment by kristen668** [comment]
Hi @benkarl, I tried update to v201809, running into same issue. When I click on error, it directs me to the cast.py file, this is a screenshot of the lines where the error message directs me to: 
<img width="321" alt="Screen Shot 2019-03-14 at 11 59 20 AM" src="https://user-images.githubusercontent.com/48520593/54371903-9f923d00-4650-11e9-8a1d-2e36fe3d7ba2.png">

**Comment by BenRKarl** [comment]
Thanks @kristen668 - Can you share the full stack trace you get for this error? Also I'm curious if it's generated by a specific call made to this library. It looks like the problem is related to an int being cast to another type, so I'd like to look into whether it's a value coming from the `googleads` library or if it's a value being passed into one of the methods.

**Comment by kristen668** [comment]
Hi @BenRKarl Please see below for the full stack trace. From my understanding, it looks like the error is from googleads, when I pull the report from API, it seems the new version of API downloads some int to be string format. 
<img width="901" alt="error message" src="https://user-images.githubusercontent.com/48520593/54640045-3867f480-4a65-11e9-8623-a3158708ae34.png">

**Comment by BenRKarl** [comment]
Thank you - so the error is from the line `yesterday_AG_report['yesterday_bid'].astype(int)`. The value of that property is 'auto: 60000'. You can replicate the same error by trying `int('auto: 60000')` because that string can't be cast to an int.

What's the report this code is generating? And from which field is `yesterday_AG_report['yesterday_bid']` getting its value?

**Comment by kristen668** [comment]
Hi @BenRKarl ['yesterday_bid'] is the max bidding value from yesterday, the data is pulled directly from adwords through API.

**Comment by BenRKarl** [comment]
Thanks @kristen668! Based on the stack trace it appears as though the error is coming from within `pandas` as a result of a call to the method `bidCPCAdjustment`. The body of that method is attempting to convert the value of `yesterday_AG_report['yesterday_bid']` to an int and that's causing the error. 

Can you share the exact report request that this script is making? Also if possible can you log the value of `yesterday_AG_report['yesterday_bid']` when this script is run with `201802`?

**Comment by kristen668** [comment]
Hi @BenRKarl, 
Please see this attached screenshot for the detail of the bidCPCAdjustment method. he value of yesterday_AG_report['yesterday_bid'] is integer, for example 5650000

![Screen Shot 2019-04-03 at 5 39 35 PM](https://user-images.githubusercontent.com/48520593/55515023-866d2280-5637-11e9-9fc4-ffab66668751.png)

**Comment by BenRKarl** [comment]
@kristen668 thanks for sharing this. It still isn't exactly clear what report this is working from and what field `yesterday_bid` corresponds to on that report. I'm assuming it's the [AD_GROUP_PERFORMANCE_REPORT](https://developers.google.com/adwords/api/docs/appendix/reports/adgroup-performance-report#cpcbid) based on the name `yesterday_AG_report`. There are a number of fields in that report whose values can vary, for example please see this description for the `CpcBid` field:

```
Cost per click bid. Values can be one of: a) a money amount in micros, b) "auto: x"
or "auto" if AdWords is automatically setting the bid via the chosen bidding
strategy, or c) "--" if no CPC bid applies to the row. Values can be one of: a) a 
money amount in micros, b) "auto: x" or "auto" if this field is a bid and Google
Ads is automatically setting the bid via the chosen bidding strategy, or c) "--" if
this field is a bid and no bid applies to the row.
```

In your snippet it appears that you already have a block of code that addresses these inconsistencies in order for the values to be converted to integers. See the `for` loop under this comment in your code:

```
# To remove 'auto:' from yesterday_AG_report['yesterday_bid']
```

If you uncomment those lines it appears as though it should fix the issue.

Otherwise it appears that the API and library are functioning as expected and you just need to parse the various values that are returned from this report so they can be converted to integers.
