### ISSUE TITLE
Is it possible to add Structured Snippets?

### ISSUE THREAD

**Issue by caffeinatedMike** [googleads/googleads-python-lib#384]
I've been searching around the Google Ads Api documentation & found a reference to [Structured Snippet Ad Extensions](https://developers.google.com/adwords/api/docs/guides/structured-snippets), but they only seem to provide an example in Java on how to add them to a campaign/adgroup & a cursory search of this repository also yielded no results for how to add Structured Snippets. 

So, my question is, is it possible using this Python library? And if so, can you include an example in the library for those who may also want to accomplish this?

**Comment by BenRKarl** [comment]
Hi @caffeinatedMike thanks for posting the question! It is possible to add structured snippets using the Python library, the functionality is similar to the examples that exist in the /extensions directory. Unfortunately since we don't have an example in Python you'll need to infer the functionality from the Java example. Notice that creating a structured snippet involves sending a slightly different payload to the `CampaignExtensionSettingService`.

Also since the AdWords API is being deprecated in favor of the new Google Ads API we won't be adding new examples to this repository, but please feel free to submit issues to the new Python client library repo for any feature or example requests you have: https://github.com/googleads/google-ads-python
