### ISSUE TITLE
Request failed with invalid argument

### ISSUE THREAD

**Issue by stevenhoog** [googleads/googleads-python-lib#485]
When I try to get the campaign clicks, name and labels, filtering on campaign label resource name using the Google Ads Python library, I get the error: 'Request with ID "SbNsbrf5lx41zcFyEQZsCw" failed with status "INVALID_ARGUMENT". However, the [GAQL campaign query builder](https://developers.google.com/google-ads/api/fields/v8/campaign_query_builder), shows that it is a valid query. Can this be fixed?

` query = f"""SELECT 
            metrics.clicks,
            campaign.name, 
            campaign.labels
            FROM campaign
            WHERE campaign.labels CONTAINS ANY ('customers/XXXXXXXXXX/labels/XXXXXXXXXX') AND
            segments.date BETWEEN '2021-09-01' AND '2021-09-05' LIMIT 20"""`

**Comment by msaniscalchi** [comment]
This reported issue appears to be for the Google Ads library rather than this library.  If you happen to encounter a similar issue in the future with that library, please report it to [its issue tracker](https://github.com/googleads/google-ads-python/issues).

In the meantime, I will close this report because it is not actionable here.
