### ISSUE TITLE
Can't complete all the steps for the test network creation

### ISSUE THREAD

**Issue by MilovanovM** [googleads/googleads-python-lib#505]
According to the [code sample](https://github.com/googleads/googleads-python-lib/blob/bf734e9cdc86db9c9586643313fd4ec50fcc184c/examples/ad_manager/v202205/network_service/make_test_network.py#L42-L44), after the test network is created I can sign in to the UI, but the URL `http://www.google.com/admanager/main?networkCode=%s` points to 404

**Comment by MilovanovM** [comment]
Also, the comment in the same sample says:

> You do not need to have an Ad Manager account to run this example, but you do need to have a Google account

but the `LoadFromStorage` method reads an Ad Manager account's config

**Comment by christopherseeley** [comment]
Looks like the URL is out of date, can you try https://admanager.google.com ? 
Also, if you called `makeTestNetwork` while authenticating with a  Service Account then you'll need to add your Google account to the network in order to log in to the UI. You can do so by calling `UserService.createUsers`. You can assign the system-defined Administrator role by setting `roleId` to -1.
