### ISSUE TITLE
Protobuf Error with googleads.yaml

### ISSUE THREAD

**Issue by haylie-murray** [googleads/googleads-python-lib#509]
Hello, 

I have been getting an error of `ValueError: The client library configuration is missing the required "use_proto_plus" key. Please set this option to either "True" or "False". For more information about this option see the Protobuf Messages guide: https://developers.google.com/google-ads/api/docs/client-libs/python/protobuf-messages`,

I have read the message guide and have added `use_proto_plust: True` to the https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml. I am still getting this error, is there something I might be missing?

**Comment by BenRKarl** [comment]
@haylie-murray - where exactly did you add the `use_proto_plus` key? Was it in the yaml file that you're using to initialize your GoogleAdsClient instance? If you're using a different initialization work flow, i.e. `load_from_dict`, you will need to add this key to that configuration.

**Comment by msaniscalchi** [comment]
This seems relevant to the newer [google-ads-python](https://github.com/googleads/google-ads-python) library for Google Ads rather than this library. Likewise, there hasn't been any activity since the initial response, so I will close this under the assumption that the earlier guidance resolved the issue.
