### ISSUE TITLE
AdWords API which you are accessing has been discontinued. Use the new Google Ads API instead.

### ISSUE THREAD

**Issue by downdawn** [googleads/googleads-python-lib#513]
Is the AdWords API completely unavailable? How do I smoothly migrate to the Google Ads API? thank you

**Comment by wihl** [comment]
Hi @downdawn, yes the AdWords API is completely unavailable as of April 27, 2022. See this blog post: https://ads-developers.googleblog.com/2022/03/the-adwords-api-sunsets-on-april-27-2022.html

In order to migrate, follow the instructions found at https://developers.google.com/google-ads/api/docs/migration
