### ISSUE TITLE
Error: No module named 'google.api_core

### ISSUE THREAD

**Issue by iberchid** [googleads/googleads-python-lib#523]
I am trying to run the example `get_campaigns_by_label.py`, but I am getting the error below:

```
  File "/home/iberchid/Gitlab-Repos/bi/google-ads-python-main/google/ads/googleads/__init__.py", line 18, in <module>
    import google.ads.googleads.client
  File "/home/iberchid/Gitlab-Repos/bi/google-ads-python-main/google/ads/googleads/client.py", line 20, in <module>
    from google.api_core.gapic_v1.client_info import ClientInfo
ModuleNotFoundError: No module named 'google.api_core'
```

In fact, there is no such a file as `api_core.py` under `google` folder. Could you please provide some hints? Am I missing something?

**Comment by msaniscalchi** [comment]
It doesn't look like you're referring to this library. The names are similar due to some shared history, but the repository you're looking for appears to be [this one](https://github.com/googleads/google-ads-python/blob/main/google/ads/googleads/__init__.py#L18).

I'd recommend reaching out to their issue tracker about the issue.
