### ISSUE TITLE
Is there a way to get all apps that are on the report and not on the inventory?

### ISSUE THREAD

**Issue by Shaharbad** [googleads/googleads-python-lib#530]
Hey everyone,
I'll explain my question better:
When i use _getMobileApplicationsByStatement_ as seen here- https://developers.google.com/ad-manager/api/reference/v202308/MobileApplicationService , I can successfully get a list of every application I have in my inventory.
However, there are some apps that I would be able to see on the report on the UI that are not on my inventory, but not when i use _getMobileApplicationsByStatement_ with the API.

Can I somehow get that?

**Comment by christopherseeley** [comment]
For API capability related questions, please use the [Google Ad Manager API Forum](https://groups.google.com/g/google-doubleclick-for-publishers-api) instead of Github issues. These are intended to track issues with the Python client library.

The MobileApplicationService will only include applications you have "claimed" and added to your network.

**Comment by Shaharbad** [comment]
@christopherseeley Thank you
could you also answer this please?
https://github.com/googleads/googleads-python-lib/issues/528
