### ISSUE TITLE
Keyword Performance (AdWords) report downloads are empty

### ISSUE THREAD

**Issue by JasperKock** [googleads/googleads-python-lib#56]
Hi,

Since yesterday I face some problems with downloading the keyword performance report (only shows the 2 header and footer lines). My code is below.
The strange thing is: other reports like AdPerformance work like expected, while using the same code. Also, downloading the Keyword report via .NET (we are migrating from .NET > Python) works just fine with the same API version. 

When I exclude the Date column from my selection, the report will start downloading, but returns 500 MB gzipped (while it should be around 1 MB). I still put daterangetype to yesterday.

Anyone facing the same problems?

My code: 

from googleads import adwords

def main(client):

    report_downloader = client.GetReportDownloader(version='v201502')

    report = {'reportName': 'KeyWordPerformance',
              'dateRangeType': 'YESTERDAY',
              'reportType': 'KEYWORDS_PERFORMANCE_REPORT',
              'downloadFormat': 'GZIPPED_CSV',
              'selector': {
                  'fields': ["KeywordText", "AdGroupId", "CampaignId", "FirstPageCpc", "Id", "KeywordMatchType",
                             "QualityScore", "CriteriaDestinationUrl", "Date"]
              }
              }

    report_file = open(<FileName>,  'wb')

    report_downloader.DownloadReport(report, report_file)

    report_file.close()

adwords_client = adwords.AdWordsClient.LoadFromStorage()
adwords_client.SetClientCustomerId(<Specific Client>)
main(adwords_client)

**Comment by msaniscalchi** [comment]
Hello, thanks for the report. I'll take a look and get back to you on this.

**Comment by PeterJacob** [comment]
I dug a little deeper into this. The code above eventually calls _DownloadReportAsStream(). This function does a http call with urllib2 with the following parameters (without the date column):
self._end_point: https://adwords.google.com/api/adwords/reportdownload/v201502
post_body: __rdxml=<tns:reportDefinition+xmlns:tns="https://adwords.google.com/api/adwords/cm/v201502">%0A+++<tns:selector>%0A++++++<tns:fields>KeywordText</tns:fields>%0A++++++<tns:fields>AdGroupId</tns:fields>%0A++++++<tns:fields>CampaignId</tns:fields>%0A++++++<tns:fields>FirstPageCpc</tns:fields>%0A++++++<tns:fields>Id</tns:fields>%0A++++++<tns:fields>KeywordMatchType</tns:fields>%0A++++++<tns:fields>QualityScore</tns:fields>%0A++++++<tns:fields>CriteriaDestinationUrl</tns:fields>%0A+++</tns:selector>%0A+++<tns:reportName>KeyWordPerformance</tns:reportName>%0A+++<tns:reportType>KEYWORDS_PERFORMANCE_REPORT</tns:reportType>%0A+++<tns:dateRangeType>YESTERDAY</tns:dateRangeType>%0A+++<tns:downloadFormat>CSV</tns:downloadFormat>%0A</tns:reportDefinition>

or with the date column:

self._end_point: https://adwords.google.com/api/adwords/reportdownload/v201502
post_body: __rdxml=<tns:reportDefinition+xmlns:tns="https://adwords.google.com/api/adwords/cm/v201502">%0A+++<tns:selector>%0A++++++<tns:fields>KeywordText</tns:fields>%0A++++++<tns:fields>AdGroupId</tns:fields>%0A++++++<tns:fields>CampaignId</tns:fields>%0A++++++<tns:fields>FirstPageCpc</tns:fields>%0A++++++<tns:fields>Id</tns:fields>%0A++++++<tns:fields>KeywordMatchType</tns:fields>%0A++++++<tns:fields>QualityScore</tns:fields>%0A++++++<tns:fields>CriteriaDestinationUrl</tns:fields>%0A++++++<tns:fields>Date</tns:fields>%0A+++</tns:selector>%0A+++<tns:reportName>KeyWordPerformance</tns:reportName>%0A+++<tns:reportType>KEYWORDS_PERFORMANCE_REPORT</tns:reportType>%0A+++<tns:dateRangeType>YESTERDAY</tns:dateRangeType>%0A+++<tns:downloadFormat>CSV</tns:downloadFormat>%0A</tns:reportDefinition>

The header contains passwords an such, so I won't paste it here :)

The only difference between the two request bodies is: ++++++<tns:fields>Date</tns:fields>
This seems totaly normal. We also tried the old python API, and it has the same problem. So it seems like there is a problem in the backend.

**Comment by msaniscalchi** [comment]
Thanks for looking into it. Yes, I've replicated the behavior with the Date as well. It doesn't appear to be related to the Python client library. I'm in discussions with the AdWords team to verify if there is any plausible explanation for this, although my judgement call at the moment would be that it probably isn't intended behavior.

Aside from that though, all of the other described behavior is working as expected. Since no metric fields are being selected in the report definition (only attributes and segments are), it is normal for the report to be empty. See the [Reporting Concepts Guide](https://developers.google.com/adwords/api/docs/guides/reporting-concepts#mandatory-fields) for more information on this topic.

I'll continue looking into the unexpected behavior with the Date field.

**Comment by msaniscalchi** [comment]
Nope, turns out it was expected behavior after all. Check out the [Zero Impression Reports Guide](https://developers.google.com/adwords/api/docs/guides/zero-impression-reports#summary).

When you're getting a non-empty report, that is a Zero Impression Report. The date field is a segment, which implicitly filters zero impression rows. That is why you're seeing an empty report when you include the Date field.
