### ISSUE TITLE
Support Python 2.7.9+ since ssl is reimplemented and it will not works!

### ISSUE THREAD

**Issue by ChameleonRed** [googleads/googleads-python-lib#60]
See all problem reported in Stackoverflow and ask about more information if it need.

http://stackoverflow.com/questions/30704894/why-i-receive-certificate-verify-failed-from-google-adwords-api

http://stackoverflow.com/questions/30705065/how-to-add-certificate-or-authority-to-trusted-list-in-python-2-7

http://stackoverflow.com/questions/30707777/how-to-connect-with-ssl-to-https-server-in-python-2-7-10-and-make-certificate-t

**Comment by msaniscalchi** [comment]
Thanks for the report! We're considering a few options, but we do intend to add support for this. We'll update this bug when we've made the release for it.

**Comment by msaniscalchi** [comment]
Hello, just providing an update on this. Python 2.7.9 is now the minimum recommended version for this library; you could hypothetically use earlier Python 2 versions like Python 2.7.6, but it is not recommended because you'd be missing out on the important SSL Certificate Validation feature introduced in Python 2.7.9.

I'm not certain if this really resolves your problem, because I think there is something else going on in those linked topics. For example, it's peculiar that the certificate from the API endpoint isn't valid for you. You shouldn't need to make any changes for it to work. Feel free to provide more details if I'm missing something here.
