### ISSUE TITLE
Inconsistent CustomerService response with Ads Py Google

### ISSUE THREAD

**Issue by btourtellott** [googleads/googleads-python-lib#67]
One difference between Google Ads and Ads Py Google is when sending a get operation to CustomerService requesting a specific customer has not fully set up there account. In Ads Py Google, an empty dictionary would be returned. In Google Ads, ```None``` is returned.

Are you guys aware of this difference? I am curious if this is expected behavior, and if it is something that we should expect going forward.

**Comment by nicholaschen** [comment]
Not an owner on AdWords, but this seems to be expected behavior since the library itself returns 'Suds' packed objects on response - which will be an object in the Suds model rather than a straight dictionary (note the behavioral difference of accepting object[key] but not object.get(key) showing the divergence from a dict)

Behaviorally they're similar in that evaluating if {} vs. if None should result. If this is something that's breaking your process, definitely let us know how it's doing so - maybe we're just not aware of a use-case :)
