### ISSUE TITLE
How to use "Compress SOAP messages" listed on best practices article.

### ISSUE THREAD

**Issue by cenouro** [googleads/googleads-python-lib#77]
I would like to know how do I enable usage of compressed SOAP messages using this lib. I have taken a look at the source code and some sections have a 'gzip' on options `kwargs`, but it is not clear if I have to do further configuration and/or if the lib already uses gziped SOAP messages by default.

**Comment by msaniscalchi** [comment]
Hello, could you link the article you're referencing? As far as I'm aware, there are no explicit settings for this in suds-jurko, so I wouldn't expect compression to be enabled.

**Comment by josepsanz** [comment]
I had this problem a year ago. I use [jurko release-0.4] (https://bitbucket.org/jurko/suds/src/81868f6f5bad4fc254b72af0f08a9597588f5c72?at=release-0.4.1%20jurko%201) and, as far as I know, has no support to deal with [compress data] (https://bitbucket.org/jurko/suds/issues/16/suds-crashes-when-server-returns-gzip) so I did a quick and dirty internal patch in my work project that it is still there :(

Here my workaround:

* In _*suds-jurko*_ module, in order to replace [*_send_*] (https://bitbucket.org/jurko/suds/src/81868f6f5bad4fc254b72af0f08a9597588f5c72/suds/transport/http.py?at=release-0.4.1+jurko+1&fileviewer=file-view-default#http.py-67) method functionality, add a new handmade method called _my_send_  just above _send_ signature:
```python 
import gzip, CStringIO

def my_send(self, request, retry=1):
    try:
        if (request.headers['content-encoding'] == 'gzip'):
            ss = cStringIO.StringIO()
            gzip.GzipFile(fileobj=ss, mode='w').write(request.message)
            body = ss.getvalue()
        else:
            body = request.message
    except KeyError:
        pass

    h = httplib2.Http(".cache")
    log.debug('sending:\n%s', request)
    resp, content = h.request(request.url, method='POST', headers=request.headers, body=body)
    log.debug('received:\n%s', content)

    code = int(resp['status'])
    if code in (200, ):
        return Reply(code, request.headers, content)
    elif code in (202, 204):
        return Reply(code, request.headers, None)
    elif code in (500,) and retry:
        log.warning('Retry: {0}\n{1}'.format(retry, resp))
        time.sleep(0.5)
        return self.adpure_send(request, retry-1)
    else:
        raise TransportError(content, code, cStringIO.StringIO(content))
```
* In _*suds-jurko*_ module, replace _send_ call method by _my_send_, [suds-jurko:640](https://bitbucket.org/jurko/suds/src/81868f6f5bad4fc254b72af0f08a9597588f5c72/suds/client.py?at=release-0.4.1+jurko+1&fileviewer=file-view-default#client.py-640):
```python
#reply = transport.send(request)
reply = transport.my_send(request)
```
* After that, in _*googleads-python-lib*_, propagate http header along _adword.py_ file in order to reach target suds object. Modify these lines:

https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L231 
```python
#def GetService(self, service_name, version=sorted(_SERVICE_MAP.keys())[-1], server=_DEFAULT_ENDPOINT):
def GetService(self, service_name, version=sorted(_SERVICE_MAP.keys())[-1], server=_DEFAULT_ENDPOINT, my_http_headers={}):
```

https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L274
```python
#return googleads.common.SudsServiceProxy(client, _AdWordsHeaderHandler(self, version))
return googleads.common.SudsServiceProxy(client, _AdWordsHeaderHandler(self, version, my_http_headers))
```

https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L317
```python
#def __init__(self, adwords_client, version):
def __init__(self, adwords_client, version, my_http_headers):
```

* In _*googleads-python-lib*_, add this new line after [adwords.py:328](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L328)
```
self._my_http_headers = my_http_headers
```

* In _*googleads-python-lib*_, modify _SetHeader_ method in order to pass _my_http_headers_ to suds object [adwords.py:330](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L330)
```python
def SetHeaders(self, suds_client):
    """Sets the SOAP and HTTP headers on the given suds client."""
    header = suds_client.factory.create(self._SOAP_HEADER_CLASS % self._version)
    header.clientCustomerId = self._adwords_client.client_customer_id
    header.developerToken = self._adwords_client.developer_token
    header.userAgent = ''.join([self._adwords_client.user_agent, self._LIB_SIG])
    header.validateOnly = self._adwords_client.validate_only
    header.partialFailure = self._adwords_client.partial_failure

    my_http_headers = self._adwords_client.oauth2_client.CreateHttpHeader()
    my_http_headers.update(self._my_http_headers)

    suds_client.set_options(
        soapheaders=header,
        headers=my_http_headers)
```

* Finally, in your own project, do something like this:
```python
...
my_http_headers = {
    'accept-encoding': 'gzip',
    'content-encoding': 'gzip',
    'user-agent': ''.join(['my_user_agent', ' (gzip)'])
    }
customer.GetService(service_name, version=version, my_http_headers=my_http_headers)
...
```

That's all! 
Keep in mind, this is a kludge!

**Comment by cenouro** [comment]
Here is the [reference article](https://developers.google.com/adwords/api/docs/guides/bestpractices?hl=en#gzip_soap). It seems that the `LoadFromStorage` method actually parses the `user_agent` on the yaml file, but nothing is specified about the `Accept-Encoding` described on the reference.

@josepsanz, thanks dude. I will give your implementation a try. But I still wanted something out of the box since these kinda of patches can become obscure code and a pain to keep a track together with my project itself.
