### ISSUE TITLE
logging with report download

### ISSUE THREAD

**Issue by Olmer1st** [googleads/googleads-python-lib#84]
Hi,
when using below commands together with report downloading
logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.transport').setLevel(logging.DEBUG)

nothing shown in console.
But if i use the same commands together with CustomerService, i can see all transport information.
Thanks

**Comment by msaniscalchi** [comment]
Thanks for the report! The commands you used provide more logs for services because suds.transport is involved in the actual API call. Reports are a little different, because urllib2 is used to perform the request. Unfortunately urllib2 doesn't offer a nice way of setting logging like this.

We'll look into this for the next release.

**Comment by Olmer1st** [comment]
Hi,
I have the same problem, it's very important to provide the input and output log for download reports.
Currently it's not happens.

**Comment by Olmer1st** [comment]
Hi,
do you have an progress with this issue?

**Comment by msaniscalchi** [comment]
This will be resolved in the next release.
