### ISSUE TITLE
AdWords errors come as an object instead of list when there's only one error

### ISSUE THREAD

**Issue by lewis-grimmett** [googleads/googleads-python-lib#90]
When using mutate methods, if there's a single error (e.g. Policy Violation) then the 'errors' element of the response is an object instead of a list.
except suds.WebFault, e:
&nbsp;&nbsp;e.fault.detail.ApiExceptionFault.errors

The sample in /examples/adwords/v201506/error_handling/handle_policy_violation_error.py line 68:

except suds.WebFault, e:
&nbsp;&nbsp;for error in e.fault.detail.ApiExceptionFault.errors:
&nbsp;&nbsp;&nbsp;&nbsp;if error['ApiError.Type'] == 'PolicyViolationError':

For a single error, the loop cycles through tuples of the keys in the error, not through distinct errors. This raises a KeyError exception on the if statment.

Current Workaround:
except suds.WebFault, e:
&nbsp;&nbsp;if isinstance(e.fault.detail.ApiExceptionFault.errors, list):
&nbsp;&nbsp;&nbsp;&nbsp;errors = e.fault.detail.ApiExceptionFault.errors
&nbsp;&nbsp;else:
&nbsp;&nbsp;&nbsp;&nbsp;errors = [e.fault.detail.ApiExceptionFault.errors]
&nbsp;&nbsp;for error in errors:
&nbsp;&nbsp;&nbsp;&nbsp;if error['ApiError.Type'] == 'PolicyViolationError':

I've seen this using both the AdGroupAdService and the AdGroupCriterionService. With more than one error, behaviour is correct.

Thanks

**Comment by msaniscalchi** [comment]
Hello, thanks for bringing this to our attention! I was able to confirm this behavior on our end.

We're looking into this. To be clear, this isn't expected behavior. We should be receiving a list regardless of the number of errors, so the incorrect behavior here is actually that the object was returned rather than how the exception handling was... handled.
