### ISSUE TITLE
Client ID/ Secret check in generate_refresh_token.py seems broken

### ISSUE THREAD

**Issue by patrick--** [googleads/googleads-python-lib#92]
An exception is raised when you give values to `CLIENT_SECRET` and or `CLIENT_ID` and execute the program without passing `--client_id` and or `--client_secret`.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report. We're looking into this one and a fix should be made available soon.

**Comment by nicholaschen** [comment]
this was fixed in the last push (I should've put it in the README!)

https://github.com/googleads/googleads-python-lib/blob/57fe3710c6ff95554415640a82f645d894eb1f96/examples/adwords/authentication/generate_refresh_token.py

we were incorrectly checking the flag args and comparing them to the defaults, effectively making the program run through with useless values.
